### ISSUE TITLE
what is the best approach to union actions when we have more than the limited number?

### ISSUE THREAD

**Issue by cvgaviao** [cartant/ts-action#11]
The function union() supports a limited number (11) of actions to be passed as its parameters.

what would be the best approach in case my action class do have more than eleven actions ?

**Comment by cartant** [comment]
I guess the best approach is the one that you've taken: raise an issue and ask a question about the part of this library that I'm least happy with and prompt me to improve it. :smile:

Well, I've had a think about it and I have a much better way of doing it. And there won't be an arbitrary maximum number of actions. I'll publish a new version of the package later today.

**Comment by cartant** [comment]
Version 5.0.0 has been published. Instead of:

```ts
union(Foo, Bar);
```

You should now use:

```ts
union({ Foo, Bar });
```

**Comment by cartant** [comment]
Actually, it's now version 6.0.0, as I've made similar changes to `isType` and `ofType`, too.

**Comment by aarjithn** [comment]
Hi @cartant I see latest version of ts-action (11) doesn't accept passing an object into union. 
This is the error

```
Argument of type '{ increment: ((payload: IPayload) => { payload: IPayload; } & { type: "INCREMENT"; }) & { type: "INCREMENT"; }; decrement: ((payload: IPayload) => { payload: IPayload; } & { ...; }) & { ...; }; }' is not assignable to parameter of type 'Creator & { type: string; }'.
  Object literal may only specify known properties, and 'increment' does not exist in type 'Creator & { type: string; }'.ts(2345)
```

I have a codesandbox with this issue: https://codesandbox.io/s/typescript-redux-i8lwk?file=/src/reducer.ts

The usecase I'm trying to do is export an object of actions, or do an import * from actions - so that union need not be updated each time action is modified. Is there another recommended approach for this now?
