### ISSUE TITLE
Missing payload param in reducer doesn't get flagged by typescript

### ISSUE THREAD

**Issue by will-stone** [cartant/ts-action#25]
First of all, thank-you very much for this lib; it is the best package I've found for reducing action boilerplate.

I've found that typescript allows this to go through: 
```ts
...
test: state.test === 'bar' ? 'foo' : action.payload, // <-- this bit: 'action.payload'
...
```

i.e. without specifying a payload key.

Here's a sandbox demonstrating the issue: https://codesandbox.io/s/2on52r265j

I'm trying to fix it myself and will let you know if I come up with a solution.

**Comment by cartant** [comment]
I think the issue is that the arrow function that's assigned to `reducer` does not specify a return type, so TypeScript infers the type as  `{ test: string | { str: string } }`.

TypeScript doesn't know that reducers are supposed to return the state.

If you explicitly declare the return type, TypeScript will complain:

```ts
const reducer = (
  state: { test: string } = { test: 'bar' },
  action: typeof Actions,
): { test: string } /* ... */
```

**Comment by will-stone** [comment]
Of course! Thanks 😄
