### ISSUE TITLE
More than 3 actions in reducer's on statement.

### ISSUE THREAD

**Issue by chelovekgenek** [cartant/ts-action#46]
I stacked with the problem that reducer is not doing autoresolve of handler arguments types if i will send there more than 3 action in one queue.

![image](https://user-images.githubusercontent.com/22083052/67400877-99811900-f5ae-11e9-9ff7-9cbf06e13053.png)
![image](https://user-images.githubusercontent.com/22083052/67401307-4491d280-f5af-11e9-85e9-dcc61c530186.png)

I also found hardcoded that you accepts only 3 args: `export declare function on<C1 extends ActionCreator, C2 extends ActionCreator, C3 extends ActionCreator, S>(creator1: C1, creator2: C2, creator3: C3, reducer: OnReducer<S, [C1, C2, C3]>): On<S>;`
Is this possible to make it more generic?

I really like how this library helps solving redux boilerplate code problem and i want continue using it.

**Comment by cartant** [comment]
Yeah. I can do something about this. It's the way it is because I simply could no get TypeScript todo what I wanted. I can see, now, what the problem is and that it's not something in TypeScript that is ever going to change.

I have a few ideas for a solution. And I have a question that's related: have you ever had cause to use the `union` function that's in the package? I'm considering tweaking it to use in the solution. It would be an easily-fixed breaking change and I'm wondering whether people use it often. I suppose that if you are using the `reducer` function `union` is not something you really need?

**Comment by chelovekgenek** [comment]
Thanks a lot for the quick reply.
I know about this typescript problem too. And i think that helper function that helps us to combine many action will be great solution. Shoult it be something like that?
![image](https://user-images.githubusercontent.com/22083052/67459751-92ebb380-f639-11e9-9a74-34c3cbe2c484.png)

**Comment by cartant** [comment]
Yeah. Close. It will look like this:

```
on(...union(foo, bar), (state, action) => {})
```

The fundamental problem is that TypeScript will not make a union of functions and the action creators - `foo` and `bar` - are functions. I will change the implementation of `union` so that it returns an array of action creators with the types changed so that they are not functions - the implementation of `on` will be the same. There will just be some type trickery.

Having heaps of overload signatures is something I really don't like. I think this will be a reasonable solution.

I will also change the current catch-all signature so that it will work without error. It will just lose the narrowing.

**Comment by cartant** [comment]
I've pushed the changes. If you are interested in the usage, have a look at this test:

https://github.com/cartant/ts-action/blob/f3647a763bac6425fa2ebdfee451fcbe2cb6cab9/packages/ts-action/source/reducer-spec.ts#L94-L116

If you are interested in the TypeScript behaviours that need to be worked around, have a look at these experiments:

https://github.com/cartant/ts-action/blob/master/packages/ts-action/source/reducer-experiment-spec.ts

I've make some changes to the README and will publish a new version later.

**Comment by cartant** [comment]
`v11.0.0` has been published and you can now use `union` to pass as many action creators as you like to `on`: https://github.com/cartant/ts-action/blob/master/packages/ts-action/README.md#reducer
